# Generated by Django 4.2.20 on 2025-03-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialreservation',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance to be paid', max_digits=10),
        ),
        migrations.AddField(
            model_name='specialreservation',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Initial deposit paid', max_digits=10),
        ),
        migrations.AddField(
            model_name='specialreservation',
            name='deposit_paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialreservation',
            name='driver_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daily allowance for driver(s)', max_digits=10),
        ),
        migrations.AddField(
            model_name='specialreservation',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days for the reservation'),
        ),
        migrations.AddField(
            model_name='specialreservation',
            name='has_multiple_stops',
            field=models.BooleanField(default=False, help_text='Whether the trip includes multiple stops'),
        ),
        migrations.AddField(
            model_name='specialreservation',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialreservation',
            name='is_round_trip',
            field=models.BooleanField(default=False, help_text='Whether this is a round trip reservation'),
        ),
        migrations.AddField(
            model_name='specialreservation',
            name='multi_day_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra charge for multi-day trips', max_digits=10),
        ),
        migrations.AddField(
            model_name='specialreservation',
            name='passenger_count',
            field=models.PositiveIntegerField(default=1, help_text='Estimated number of passengers'),
        ),
        migrations.AddField(
            model_name='specialreservation',
            name='return_time',
            field=models.DateTimeField(blank=True, help_text='For round trips, when the vehicle will return', null=True),
        ),
        migrations.AddField(
            model_name='specialreservation',
            name='season_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier based on high/low season', max_digits=5),
        ),
        migrations.AddField(
            model_name='specialreservation',
            name='stops',
            field=models.TextField(blank=True, help_text='Comma-separated list of stops along the way'),
        ),
        migrations.AddField(
            model_name='specialreservation',
            name='trip_purpose',
            field=models.CharField(blank=True, help_text='Purpose of the trip (e.g., Tour, Picnic, Wedding)', max_length=100),
        ),
    ]
