# Generated by Django 4.2.20 on 2025-03-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0002_specialreservation_balance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialreservation',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='specialreservation',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
