# Generated by Django 4.2.20 on 2025-03-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0003_alter_specialreservation_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dashboard', max_length=255)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard',
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
    ]
